### ISSUE TITLE
CDC shutdowns unexpectedly in bootcamp's banking application

### ISSUE THREAD

**Issue by cer** [eventuate-foundation/eventuate-cdc#101]
```
cdc-service_1             | 2020-12-19 10:12:52.471  INFO 8 --- [extShutdownHook] i.e.l.c.BinlogEntryReaderLeadership      : Stopping BinlogEntryReaderLeadership
cdc-service_1             | 2020-12-19 10:12:52.471  INFO 8 --- [extShutdownHook] i.e.l.mysql.binlog.MySqlBinaryLogClient  : Stopping MySqlBinaryLogClient
cdc-service_1             | 2020-12-19 10:12:52.477  INFO 8 --- [       Thread-8] i.e.l.mysql.binlog.MySqlBinaryLogClient  : MySqlBinaryLogClient finished processing
cdc-service_1             | 2020-12-19 10:12:52.482  INFO 8 --- [extShutdownHook] i.e.l.mysql.binlog.MySqlBinaryLogClient  : Stopped MySqlBinaryLogClient
cdc-service_1             | 2020-12-19 10:12:52.483  INFO 8 --- [extShutdownHook] i.e.c.l.zookeeper.ZkLeaderSelector       : Closing leader selector, leaderId : 0c9cb800-d232-4d3e-926b-8ba9bc070ab2
cdc-service_1             | 2020-12-19 10:12:52.491  INFO 8 --- [extShutdownHook] i.e.c.l.zookeeper.ZkLeaderSelector       : Closed leader selector, leaderId : 0c9cb800-d232-4d3e-926b-8ba9bc070ab2
cdc-service_1             | 2020-12-19 10:12:52.491  INFO 8 --- [extShutdownHook] i.e.l.c.BinlogEntryReaderLeadership      : Stopped BinlogEntryReaderLeadership
cdc-service_1             | 2020-12-19 10:12:52.520  INFO 8 --- [extShutdownHook] i.e.local.common.CdcDataPublisher        : Stopping CdcDataPublisher
cdc-service_1             | 2020-12-19 10:12:52.521  INFO 8 --- [extShutdownHook] .p.w.k.EventuateKafkaDataProducerWrapper : closing EventuateKafkaDataProducerWrapper
cdc-service_1             | 2020-12-19 10:12:52.522  INFO 8 --- [extShutdownHook] o.a.k.clients.producer.KafkaProducer     : [Producer clientId=producer-2] Closing the Kafka producer with timeoutMillis = 1000 ms.
cdc-service_1             | 2020-12-19 10:12:52.551 ERROR 8 --- [eaderSelector-0] i.e.c.l.zookeeper.ZkLeaderSelector       : Leadership interrupted
cdc-service_1             | 
cdc-service_1             | java.lang.InterruptedException: null
cdc-service_1             | 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:998) ~[na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304) ~[na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231) ~[na:1.8.0_252]
cdc-service_1             | 	at io.eventuate.coordination.leadership.zookeeper.ZkLeaderSelector$1.takeLeadership(ZkLeaderSelector.java:67) ~[eventuate-common-coordination-leadership-zookeeper-0.9.0.RELEASE.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector$WrappedListener.takeLeadership(LeaderSelector.java:534) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:399) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:441) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_252]
cdc-service_1             | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
cdc-service_1             | 
cdc-service_1             | 2020-12-19 10:12:52.554  INFO 8 --- [extShutdownHook] .p.w.k.EventuateKafkaDataProducerWrapper : closed EventuateKafkaDataProducerWrapper
cdc-service_1             | 2020-12-19 10:12:52.555  INFO 8 --- [extShutdownHook] i.e.local.common.CdcDataPublisher        : Stopped CdcDataPublisher
cdc-service_1             | 2020-12-19 10:12:52.555  INFO 8 --- [extShutdownHook] i.e.local.common.CdcDataPublisher        : Stopping CdcDataPublisher
cdc-service_1             | 2020-12-19 10:12:52.555  INFO 8 --- [extShutdownHook] .p.w.k.EventuateKafkaDataProducerWrapper : closing EventuateKafkaDataProducerWrapper
cdc-service_1             | 2020-12-19 10:12:52.555  INFO 8 --- [extShutdownHook] o.a.k.clients.producer.KafkaProducer     : [Producer clientId=producer-3] Closing the Kafka producer with timeoutMillis = 1000 ms.
cdc-service_1             | 2020-12-19 10:12:52.552  INFO 8 --- [eaderSelector-0] i.e.c.l.zookeeper.ZkLeaderSelector       : Calling leaderRemovedCallback, leaderId : 0c9cb800-d232-4d3e-926b-8ba9bc070ab2
cdc-service_1             | 2020-12-19 10:12:52.561  INFO 8 --- [eaderSelector-0] i.e.l.c.BinlogEntryReaderLeadership      : Resigning leadership
cdc-service_1             | 2020-12-19 10:12:52.562  INFO 8 --- [eaderSelector-0] i.e.l.mysql.binlog.MySqlBinaryLogClient  : Stopping MySqlBinaryLogClient
cdc-service_1             | 2020-12-19 10:12:52.562  INFO 8 --- [eaderSelector-0] i.e.l.c.BinlogEntryReaderLeadership      : Resigned leadership
cdc-service_1             | 2020-12-19 10:12:52.562  INFO 8 --- [eaderSelector-0] i.e.c.l.zookeeper.ZkLeaderSelector       : Called leaderRemovedCallback, leaderId : 0c9cb800-d232-4d3e-926b-8ba9bc070ab2
cdc-service_1             | 2020-12-19 10:12:52.574  INFO 8 --- [extShutdownHook] .p.w.k.EventuateKafkaDataProducerWrapper : closed EventuateKafkaDataProducerWrapper
cdc-service_1             | 2020-12-19 10:12:52.576  INFO 8 --- [extShutdownHook] i.e.local.common.CdcDataPublisher        : Stopped CdcDataPublisher
cdc-service_1             | 2020-12-19 10:12:52.578  INFO 8 --- [extShutdownHook] o.a.k.clients.producer.KafkaProducer     : [Producer clientId=producer-1] Closing the Kafka producer with timeoutMillis = 1000 ms.
cdc-service_1             | 2020-12-19 10:12:52.590  INFO 8 --- [tor-Framework-0] o.a.c.f.imps.CuratorFrameworkImpl        : backgroundOperationsLoop exiting
cdc-service_1             | 2020-12-19 10:12:52.593 ERROR 8 --- [eaderSelector-0] o.a.c.f.recipes.leader.LeaderSelector    : The leader threw an exception
cdc-service_1             | 
cdc-service_1             | java.lang.InterruptedException: null
cdc-service_1             | 	at java.lang.Object.wait(Native Method) ~[na:1.8.0_252]
cdc-service_1             | 	at java.lang.Object.wait(Object.java:502) ~[na:1.8.0_252]
cdc-service_1             | 	at org.apache.zookeeper.ClientCnxn.submitRequest(ClientCnxn.java:1342) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
cdc-service_1             | 	at org.apache.zookeeper.ZooKeeper.delete(ZooKeeper.java:871) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
cdc-service_1             | 	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:250) ~[curator-framework-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.imps.DeleteBuilderImpl$5.call(DeleteBuilderImpl.java:244) ~[curator-framework-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.RetryLoop.callWithRetry(RetryLoop.java:108) ~[curator-client-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.imps.DeleteBuilderImpl.pathInForeground(DeleteBuilderImpl.java:240) ~[curator-framework-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:225) ~[curator-framework-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.imps.DeleteBuilderImpl.forPath(DeleteBuilderImpl.java:35) ~[curator-framework-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.locks.LockInternals.deleteOurPath(LockInternals.java:339) ~[curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.locks.LockInternals.releaseLock(LockInternals.java:123) ~[curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.locks.InterProcessMutex.release(InterProcessMutex.java:154) ~[curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWork(LeaderSelector.java:425) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector.doWorkLoop(LeaderSelector.java:441) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector.access$100(LeaderSelector.java:64) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:245) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at org.apache.curator.framework.recipes.leader.LeaderSelector$2.call(LeaderSelector.java:239) [curator-recipes-2.11.0.jar!/:na]
cdc-service_1             | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_252]
cdc-service_1             | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_252]
cdc-service_1             | 	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
cdc-service_1             | 
distributed-data-patterns-bootcamp-banking-example_kafka_1 exited with code 255
distributed-data-patterns-bootcamp-banking-example_cdc-service_1 exited with code 255
```

**Comment by cer** [comment]
* `extShutdownHook` - is this the Spring Boot shutdown thread?
* `cdc-service_1             | 2020-12-19 10:12:52.471  INFO 8 --- [extShutdownHook] i.e.l.c.BinlogEntryReaderLeadership      : Stopping BinlogEntryReaderLeadership` - this method is only invoked by an @PreDestroy

It's unclear why it's shutting down.
