### ISSUE TITLE
CDC-service never get healthy

### ISSUE THREAD

**Issue by brokenbrains** [eventuate-foundation/eventuate-cdc#102]
Hi, i run eventuate-cdc in docker-compose provided by example.

when i run on mac machine no issue.

when i run on centos machine when i inspect the log got this

```
#######
#        #    #  ######  #    #   #####  #    #    ##     #####  ######
#        #    #  #       ##   #     #    #    #   #  #      #    #
#####    #    #  #####   # #  #     #    #    #  #    #     #    #####
#        #    #  #       #  # #     #    #    #  ######     #    #
#         #  #   #       #   ##     #    #    #  #    #     #    #
#######    ##    ######  #    #     #     ####   #    #     #    ######

2021-01-12 05:16:27.381  INFO 7 --- [           main] i.e.cdc.main.EventuateCdcServiceMain     : Starting EventuateCdcServiceMain on ae9e6490b298 with PID 7 (/eventuate-cdc-service-0.2.0.RELEASE.jar started by root in /)
2021-01-12 05:16:27.388  INFO 7 --- [           main] i.e.cdc.main.EventuateCdcServiceMain     : No active profile set, falling back to default profiles: default
2021-01-12 05:16:30.620  INFO 7 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
2021-01-12 05:16:30.661  INFO 7 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-01-12 05:16:30.661  INFO 7 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/9.0.13
2021-01-12 05:16:30.695  INFO 7 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2021-01-12 05:16:30.847  INFO 7 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-01-12 05:16:30.847  INFO 7 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3086 ms
2021-01-12 05:16:32.347  INFO 7 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-01-12 05:16:32.554  WARN 7 --- [           main] o.a.c.retry.ExponentialBackoffRetry      : maxRetries too large (2147483647). Pinning to 29
2021-01-12 05:16:32.701  INFO 7 --- [           main] o.a.c.f.imps.CuratorFrameworkImpl        : Starting
2021-01-12 05:16:32.717  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
2021-01-12 05:16:32.717  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:host.name=ae9e6490b298
2021-01-12 05:16:32.717  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.version=1.8.0_252
2021-01-12 05:16:32.717  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.vendor=Oracle Corporation
2021-01-12 05:16:32.718  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.home=/usr/local/openjdk-8/jre
2021-01-12 05:16:32.718  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.class.path=eventuate-cdc-service-0.2.0.RELEASE.jar
2021-01-12 05:16:32.718  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
2021-01-12 05:16:32.718  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.io.tmpdir=/tmp
2021-01-12 05:16:32.718  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:java.compiler=<NA>
2021-01-12 05:16:32.718  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:os.name=Linux
2021-01-12 05:16:32.723  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:os.arch=amd64
2021-01-12 05:16:32.724  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:os.version=4.18.0-147.3.1.el8_1.x86_64
2021-01-12 05:16:32.724  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:user.name=root
2021-01-12 05:16:32.724  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:user.home=/root
2021-01-12 05:16:32.724  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Client environment:user.dir=/
2021-01-12 05:16:32.726  INFO 7 --- [           main] org.apache.zookeeper.ZooKeeper           : Initiating client connection, connectString=zookeeper:2181 sessionTimeout=60000 watcher=org.apache.curator.ConnectionState@7bbc8656
2021-01-12 05:16:32.759  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:32.839  INFO 7 --- [           main] o.a.k.clients.producer.ProducerConfig    : ProducerConfig values: 
	acks = all
	batch.size = 16384
	bootstrap.servers = [kafka:29092]
	buffer.memory = 33554432
	client.dns.lookup = default
	client.id = 
	compression.type = none
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 120000
	enable.idempotence = false
	interceptor.classes = []
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 1
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 0
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = null
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = GSSAPI
	security.protocol = PLAINTEXT
	send.buffer.bytes = 131072
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
	ssl.endpoint.identification.algorithm = https
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLS
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.ByteArraySerializer

2021-01-12 05:16:32.970  INFO 7 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka version: 2.3.0
2021-01-12 05:16:32.973  INFO 7 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: fc1aaa116b661c8a
2021-01-12 05:16:32.973  INFO 7 --- [           main] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1610428592967
2021-01-12 05:16:33.057  INFO 7 --- [           main] i.e.l.u.c.p.CdcPipelineConfigurator      : Starting unified cdc pipelines
2021-01-12 05:16:33.209  INFO 7 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2021-01-12 05:16:33.816  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:34.069  WARN 7 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node -1 (kafka/172.22.0.6:29092) could not be established. Broker may not be available.
2021-01-12 05:16:34.918  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:35.921  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:37.022  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:38.033  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:39.134  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:40.146  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:41.246  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:42.257  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:43.358  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:44.369  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:45.470  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:46.481  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:47.582  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:48.593  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:49.361  WARN 7 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node -1 (kafka/172.22.0.6:29092) could not be established. Broker may not be available.
2021-01-12 05:16:49.694  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:50.578  WARN 7 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node -1 (kafka/172.22.0.6:29092) could not be established. Broker may not be available.
2021-01-12 05:16:51.857  WARN 7 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node -1 (kafka/172.22.0.6:29092) could not be established. Broker may not be available.
2021-01-12 05:16:53.265  WARN 7 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node -1 (kafka/172.22.0.6:29092) could not be established. Broker may not be available.
2021-01-12 05:16:55.185  WARN 7 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node -1 (kafka/172.22.0.6:29092) could not be established. Broker may not be available.
2021-01-12 05:16:56.786  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:57.887  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:58.897  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:16:59.998  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:17:01.009  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:17:02.111  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:17:03.121  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:17:04.222  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:17:05.233  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:17:06.334  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:17:07.346  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:17:08.447  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:17:09.458  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:17:10.558  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:17:11.570  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:17:11.889  WARN 7 --- [ad | producer-1] org.apache.kafka.clients.NetworkClient   : [Producer clientId=producer-1] Connection to node -1 (kafka/172.22.0.6:29092) could not be established. Broker may not be available.
2021-01-12 05:17:12.671  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:17:15.730  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_252]
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714) ~[na:1.8.0_252]
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:361) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081) ~[zookeeper-3.4.6.jar!/:3.4.6-1569965]

2021-01-12 05:17:16.830  INFO 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Opening socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
....
```

any idea to resolve it?

**Comment by cer** [comment]
This is the key error:
```
socket connection to server penril-wallet_zookeeper_1.penril-wallet_default/172.22.0.5:2181. Will not attempt to authenticate using SASL (unknown error)
2021-01-12 05:16:35.921  WARN 7 --- [t_default:2181)] org.apache.zookeeper.ClientCnxn          : Session 0x0 for server null, unexpected error, closing socket connection and attempting reconnect

java.net.NoRouteToHostException: No route to host
	at sun.nio.ch.SocketChannelImpl.
```

The ZK hostname looks unusual. What's the configuration in docker compose file?

/Cc @dartartem
