### ISSUE TITLE
ServerException: Could not find first log file name in binary log index file

### ISSUE THREAD

**Issue by muradhajiyev** [eventuate-foundation/eventuate-cdc#109]
My microservice application has been deployed in the Kubernetes:

- some services
- cdc-service
- kafka (with persistent volume)
- zookeeper

After the first deployment, everything worked well. I just wanted to restart my kafka pods to test failing case. Since there's persistent volume for my kafka brokers, I expected that no problem will happen.

After restarting kafka brokers, pub/sub stopped to work. cdc-service didn't show any error in the log.

I restarted cdc-service. After restarting cdc-service started to show the error below:

```
2021-04-30 13:04:37.942  INFO 7 --- [ocean.com:25060] .b.MySqlBinaryLogClientLifecycleListener : Reader reader1 disconnected.
2021-04-30 13:04:42.942  INFO 7 --- [ocean.com:25060] c.g.shyiko.mysql.binlog.BinaryLogClient  : Trying to restore lost connection to private-db-mysql-nyc1-87202-do-user-8367523-0.b.db.ondigitalocean.com:25060
2021-04-30 13:04:42.968  INFO 7 --- [ocean.com:25060] c.g.shyiko.mysql.binlog.BinaryLogClient  : Connected to private-db-mysql-nyc1-87202-do-user-8367523-0.b.db.ondigitalocean.com:25060 at binlog.000038/9140 (sid:1, cid:5514)
2021-04-30 13:04:42.968  INFO 7 --- [ocean.com:25060] .b.MySqlBinaryLogClientLifecycleListener : Reader reader1 connected.
2021-04-30 13:04:42.969 ERROR 7 --- [ocean.com:25060] .b.MySqlBinaryLogClientLifecycleListener : Reader reader1 communication failed.
2021-04-30 13:04:42.969 ERROR 7 --- [ocean.com:25060] .b.MySqlBinaryLogClientLifecycleListener : Reader communication failed.

com.github.shyiko.mysql.binlog.network.ServerException: Could not find first log file name in binary log index file
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:926) [mysql-binlog-connector-java-0.23.2.jar!/:0.23.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:595) [mysql-binlog-connector-java-0.23.2.jar!/:0.23.2]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:839) [mysql-binlog-connector-java-0.23.2.jar!/:0.23.2]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_252]
```

**Comment by muradhajiyev** [comment]
As I understand, the binlog.000038 has been removed from binlog index file. Since kafka offset stores the last position, cdc-service wants to find that binlog file, but can't find it. 

How can I solve this problem?

**Comment by feanor777** [comment]
@muradhajiyev, as you mentioned before binlog offset position is stored in the Kafka topic offset.storage.topic in the next format:
```
key: MySqlBinlog
value: {"binlogFilename":"mysql-bin.000003","offset":635,"rowsToSkip":0}
```
In case, if you did any manipulation with binlog, and this file doesn't exist, you need to change the name of your binlog offset store key using this env variable: `EVENTUATELOCAL_CDC_OFFSET_STORE_KEY: MySqlBinlog2` (or any other name)
