### ISSUE TITLE
eventuate-cdc-service:0.4.0.RELEASE - java.lang.RuntimeException: Column with name [destination] not found

### ISSUE THREAD

**Issue by cer** [eventuate-foundation/eventuate-cdc#6]
```
java.lang.RuntimeException: Column with name [destination] not found
	at io.eventuate.local.mysql.binlog.AbstractMySqlBinlogExtractor.getValue(AbstractMySqlBinlogExtractor.java:49)
	at io.eventuate.local.mysql.binlog.AbstractMySqlBinlogExtractor.getValue(AbstractMySqlBinlogExtractor.java:33)
	at io.eventuate.local.mysql.binlog.MySqlBinlogEntryExtractor$1.getColumn(MySqlBinlogEntryExtractor.java:23)
	at io.eventuate.tram.cdc.connector.BinlogEntryToMessageConverter.convert(BinlogEntryToMessageConverter.java:12)
	at io.eventuate.tram.cdc.connector.BinlogEntryToMessageConverter.convert(BinlogEntryToMessageConverter.java:9)
	at io.eventuate.local.common.BinlogEntryHandler.publish(BinlogEntryHandler.java:32)
	at io.eventuate.local.mysql.binlog.MySqlBinaryLogClient.lambda$handleWriteRowsEvent$3(MySqlBinaryLogClient.java:237)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.eventuate.local.mysql.binlog.MySqlBinaryLogClient.handleWriteRowsEvent(MySqlBinaryLogClient.java:237)
	at io.eventuate.local.mysql.binlog.MySqlBinaryLogClient.lambda$leaderStart$1(MySqlBinaryLogClient.java:160)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.notifyEventListeners(BinaryLogClient.java:1055)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:913)
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559)
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793)
	at java.lang.Thread.run(Thread.java:745)
```

* FTGO schema per service
* Possible cause: mysqluser doesn't have access to the schema
* Stacktrace - appears to not be logged

**Comment by cer** [comment]
The user id the CDC used to retrieve the column metadata didn't have permission to access the schema:

```
19:58:18.586 [blc-mysql:3306] INFO  i.e.l.m.binlog.ColumnOrderExtractor - Table io.eventuate.local.common.SchemaAndTable@51a0c567[schema=ftgo_order_service,tableName=message] has these columns {}
```
