### ISSUE TITLE
CDC becomes unhealthy because of Reader with id MySqlReader has not received message for 158602 milliseconds"

### ISSUE THREAD

**Issue by cer** [eventuate-foundation/eventuate-cdc#86]
This issue is obscured by #84 but if the CDC runs for any length of time it becomes unhealthy:

```
{
  "status": "DOWN",
  "details": {
    "binlogEntryReaderHealthCheck": {
      "status": "DOWN",
      "details": {
        "error-1": "Reader with id MySqlReader has not received message for 266718 milliseconds",
        "detail-1": "Reader with id MySqlReader is connected"
      }
    },
    "cdcDataPublisherHealthCheck": {
      "status": "UP"
    },
    "zookeeperHealthCheck": {
      "status": "UP",
      "details": {
        "detail-1": "Connected to Zookeeper"
      }
    },
    "kafkaHealthCheck": {
      "status": "UP",
      "details": {
        "detail-1": "Connected to Kafka"
      }
    },
    "diskSpace": {
      "status": "UP",
      "details": {
        "total": 62725623808,
        "free": 33846505472,
        "threshold": 10485760
      }
    }
  }
}

```

**Comment by cer** [comment]
This problem might be responsible for failing [CircleCI builds](https://app.circleci.com/pipelines/github/eventuate-tram/eventuate-tram-examples-customers-and-orders/136/workflows/b4ad2c9f-304a-4c72-9ad7-d30133556c21/jobs/556) which are slower than local builds, which gives the CDC an opportunity to become unhealthy.

**Comment by cer** [comment]
It appears that either 

* the `CdcMonitoringDao` is not inserting messages
* the MySqlReader is not receiving or is ignoring monitoring messages
* the MySqlReader doesn't update the lastReceivedTime when it processes a monitoring message

**Comment by cer** [comment]
The `cdc_monitoring` table is being updated regularly

here are the metrics

```
eventuate_cdc_binlog_entries_processed_total{readerName="MySqlReader",} 14897.0
eventuate_cdc_mysql_event_processing_duration_seconds_count 10626.0
eventuate_cdc_mysql_event_processing_duration_seconds_sum 0.228543
eventuate_cdc_mysql_event_processing_duration_seconds_max 1.26E-5
eventuate_cdc_replication_lag_age{readerName="MySqlReader",} NaN
eventuate_cdc_mysql_message_publishing_duration_seconds_count 0.0
eventuate_cdc_mysql_message_publishing_duration_seconds_sum 0.0
eventuate_cdc_mysql_message_publishing_duration_seconds_max 0.0
eventuate_cdc_events_duplicates_total 0.0
eventuate_cdc_events_sent_total 0.0
eventuate_cdc_event_age_count 0.0
eventuate_cdc_event_age_sum 0.0
eventuate_cdc_event_age_max 0.0
eventuate_cdc_mysql_event_unprocessed_offsets 0.0
eventuate_cdc_connection_attempts_total{readerName="MySqlReader",} 1.0
eventuate_cdc_leader{readerName="MySqlReader",} 1.0
eventuate_cdc_mysql_event_first_message_time 0.0
eventuate_cdc_replication_lag_max{readerName="MySqlReader",} 0.0
eventuate_cdc_replication_lag_count{readerName="MySqlReader",} 0.0
eventuate_cdc_replication_lag_sum{readerName="MySqlReader",} 0.0
eventuate_cdc_connected_to_database{readerName="MySqlReader",} 1.0
eventuate_cdc_mysql_event_latest_message_time 0.0
```

**Comment by cer** [comment]
From the development branch the metrics make sense:

```
eventuate_cdc_replication_lag_age{readerName="MySqlReader",} NaN
eventuate_cdc_replication_lag_max{readerName="MySqlReader",} 10.0
eventuate_cdc_replication_lag_count{readerName="MySqlReader",} 21.0
eventuate_cdc_replication_lag_sum{readerName="MySqlReader",} 7483.0
```

**Comment by dartartem** [comment]
Investigated.

log:

0) used zero for last event time (https://github.com/eventuate-foundation/eventuate-cdc/issues/84), cdc starts and immediately reports that it is unhealthy. 
1) Found that monitoring inserted and updated.
2) Found that update rows event is not received.
3) Debugged shyiko connector.
Found following unlogged exception:

exception `com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1605779240000, eventType=EXT_WRITE_ROWS, serverId=1, headerLength=19, dataLength=22, nextPosition=1049, flags=0}`


cause `com.github.shyiko.mysql.binlog.event.deserialization.MissingTableMapEventException: No TableMapEventData has been found for table id:108. Usually that means that you have started reading binary log 'within the logical event group' (e.g. from WRITE_ROWS and not proceeding TABLE_MAP`

4) checked related issues on shyiko connector github page. But did not found a clue. Continued debugging.

5) found that connector expects TableMapEventData instance in `Map<Long, TableMapEventData> tableMapEventByTableId`

in update deserializer.

6) I found that by mistake I deleted adding to tableMapEventByTableId monitoring table map event:

https://github.com/eventuate-foundation/eventuate-cdc/commit/bcdf3cd970fb11fe2b688df44595950113f97be9#diff-450e9de12d2111eb2f2b87f240350cf1867ea1ae6411aae280fecac9d0187787R221

because cdc monitoring change does not require any special handling like here: https://github.com/dartartem/eventuate-cdc-1/blob/wip-db-id-gen/eventuate-local-java-cdc-connector-mysql-binlog/src/main/java/io/eventuate/local/mysql/binlog/MySqlBinaryLogClient.java#L303

7) Fixed. Now cdc is reported healthy. Because issue is reproducible by existing tests, I did not add new. Please see point 0.

8) Added [lifecycle handler](https://github.com/dartartem/eventuate-cdc-1/blob/cb3bd8315f8acd277edb6684ab782463fadaddbd/eventuate-local-java-cdc-connector-mysql-binlog/src/main/java/io/eventuate/local/mysql/binlog/MySqlBinaryLogClientLifecycleListener.java) to show exceptions like from point 3
But now on cdc start following exceptions appeared:
```

com.github.shyiko.mysql.binlog.event.deserialization.EventDataDeserializationException: Failed to deserialize data of EventHeaderV4{timestamp=1605800408000, eventType=EXT_UPDATE_ROWS, serverId=1, headerLength=19, dataLength=61, nextPosition=5506, flags=0}
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:233) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.nextEvent(EventDeserializer.java:201) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:890) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:559) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:793) [mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: com.github.shyiko.mysql.binlog.event.deserialization.MissingTableMapEventException: No TableMapEventData has been found for table id:108. Usually that means that you have started reading binary log 'within the logical event group' (e.g. from WRITE_ROWS and not proceeding TABLE_MAP
	at com.github.shyiko.mysql.binlog.event.deserialization.AbstractRowsEventDataDeserializer.deserializeRow(AbstractRowsEventDataDeserializer.java:104) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at io.eventuate.local.mysql.binlog.UpdateRowsDeserializer.deserializeRow(UpdateRowsDeserializer.java:23) ~[main/:na]
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserializeRows(UpdateRowsEventDataDeserializer.java:71) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:58) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.UpdateRowsEventDataDeserializer.deserialize(UpdateRowsEventDataDeserializer.java:33) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	at com.github.shyiko.mysql.binlog.event.deserialization.EventDeserializer.deserializeEventData(EventDeserializer.java:227) ~[mysql-binlog-connector-java-0.16.1.jar:0.16.1]
	... 5 common frames omitted
```

Appeared on cdc start on clean database.
Not yet investigated. Probably some database internal operations different from message/monitoring writes.
**Probably it is worth to add all TABLE_MAP events to** `Map<Long, TableMapEventData> tableMapEventByTableId` in [TableMapper](https://github.com/eventuate-foundation/eventuate-cdc/blob/wip-db-id-gen/eventuate-local-java-cdc-connector-mysql-binlog/src/main/java/io/eventuate/local/mysql/binlog/TableMapper.java).

**Comment by cer** [comment]
> * Fixed. Now cdc is reported healthy. Because issue is reproducible by existing tests, I did not add new. Please see point 0.
> *

Which existing tests in eventuate-cdc reproduced the problem? The BUILD-SNAPSHOTs were being built successfully despite this bug.

**Comment by dartartem** [comment]
yes, it was built fine because of #84: `lastEventTime = System.currentTimeMillis();`

now it is:` lastEventTime = 0;` With that value cdc does not start without fix.

./scripts/build-and-test-all-tram-cdc-mysql-binlog.sh reproduces it:

```
Waiting for eventuate-cdc-service_1 to become healthy (it's starting)
Waiting for eventuate-cdc-service_1 to become healthy (it's starting)
Waiting for eventuate-cdc-service_1 to become healthy (it's starting)
Waiting for eventuate-cdc-service_1 to become healthy (it's starting)
Waiting for eventuate-cdc-service_1 to become healthy (it's starting)
Waiting for eventuate-cdc-service_1 to become healthy (it's unhealthy)
Waiting for eventuate-cdc-service_1 to become healthy (it's unhealthy)
Waiting for eventuate-cdc-service_1 to become healthy (it's unhealthy)
```

**Comment by cer** [comment]
> yes, it was built fine because of #84: `lastEventTime = System.currentTimeMillis();`
> 
> now it is:` lastEventTime = 0;` With that value cdc does not start without fix.

That's for the clarification.
